create table productivity_score (
  date text primary key not null,
  score0 int not null default 0,
  score1 int not null default 0,
  score2 int not null default 0,
  score3 int not null default 0,
  score4 int not null default 0,
  score5 int not null default 0,
  score6 int not null default 0,
  score7 int not null default 0,
  score8 int not null default 0,
  score9 int not null default 0,
  score10 int not null default 0,
  score11 int not null default 0,
  score12 int not null default 0,
  score13 int not null default 0,
  score14 int not null default 0,
  score15 int not null default 0,
  score16 int not null default 0,
  score17 int not null default 0,
  score18 int not null default 0,
  score19 int not null default 0,
  score20 int not null default 0,
  score21 int not null default 0,
  score22 int not null default 0,
  score23 int not null default 0
);
